name: 'Build & Test .NET'

on:
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

env:
  SOLUTION_PATH: './Koala.Serialization.sln'

jobs:
  build-test:

    runs-on: ubuntu-latest
    
    steps:
    - name: 'Start'
      uses: actions/checkout@v3

    - name: 'Setup .Net'
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: 'Restore Dependencies'
      run: dotnet restore

    - name: 'Build Solution'
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore 

    - name: 'Run UnitTests'
      run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build 
